### ISSUE TITLE
Support Go Units

### ISSUE THREAD

**Issue by jmank88** [gochain/gochain#234]
We should update the [api](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3fromwei) to support go specific units. We have to support Ether units for backwards compatibility, but we should consider also supporting Go versions as well, e.g. `microgo`, `milligo`, `kgo`, `mgo`, `picogo`, etc.

**Comment by treeder** [comment]
Could start referring to wei as `attogo` (10^-18) and gwei as `nanogo` (10^-9).

https://www.varsitytutors.com/hotmath/hotmath_help/topics/big-and-small-numbers
