### ISSUE TITLE
Consider using IPFS for storage of older blocks - could reduce per node storage, increase availability

### ISSUE THREAD

**Issue by treeder** [gochain/gochain#259]
If we were to store blocks and parts of the merkle tree in IPFS, it could reduce the per node storage requirements dramatically, while reducing strain on those nodes as well. If each block were "pinned" on 3-5 nodes to ensure persistence, we could reduce the per node storage by a significant amount while still having fast access to blocks that aren't stored on the node. It would also make it so information could be pulled from non-signing nodes in the IPFS network.

**Comment by jmank88** [comment]
Explorer could then potentially fetch blocks directly from IPFS instead of through the proxy node RPC.
