### ISSUE TITLE
Better logging/debugging support

### ISSUE THREAD

**Issue by treeder** [gochain/gochain#354]
Without changing the data structure, it would be nice to be able to emit tx and contract event logs to a logging service for debugging and monitoring. 

This could be a global setting or a per contract setting (per contract would send logs from a specific contract to a particular logging endpoint).

**Comment by jmank88** [comment]
Does this serve any use cases not already covered by RPC PUB/SUB? https://github.com/ethereum/go-ethereum/wiki/RPC-PUB-SUB
