### ISSUE TITLE
Move all common / util packages to a separate repo?

### ISSUE THREAD

**Issue by treeder** [gochain/gochain#380]
This would allow other tools to use it without importing this huge repo. 

Some packages to consider:

* common
* crypto

**Comment by jmank88** [comment]
Does the large enclosing repo impose that much of a cost? Modules and dep bundle everything on a package level, and when they fetch the whole repo they cache it. Is there a particular use case that is slow?

Breaking them out in to separate repos would further diverge us from upstream, and complicate merging changes.
