### ISSUE TITLE
Contract failing to deploy

### ISSUE THREAD

**Issue by treeder** [gochain/gochain#413]
[This contract](https://github.com/gochain/uniswap-v2-core/blob/master/contracts/UniswapV2Factory_flatten.sol) is failing to deploy, transactions failing. 

## To Reproduce

```sh
web3 contract build UniswapV2Factory_flatten.sol
web3 contract deploy UniswapV2Factory.bin
```

Resulting transaction will fail.

**Comment by jmank88** [comment]
That contract is using features from Istanbul, but we only support through Constantinople. Targeting an earlier version during compilation produces:
```sh
Error: The "chainid" instruction is only available for Istanbul-compatible VMs  (you are currently compiling for "petersburg").
            chainId := chainid
                       ^-----^
```

**Comment by jmank88** [comment]
I was able to deploy [here](https://testnet-explorer.gochain.io/tx/0xa14746e171feca217d4079d9ee5c0e022dacc9adab220636808538c302320128) by doing a combination of things:
- using `pragma solidity =0.5.13;`
- hard coding the chain ID
- upping the gas limit to 3,000,000
- passing a constructor parameter
