### ISSUE TITLE
Add support for Rosetta API

### ISSUE THREAD

**Issue by treeder** [gochain/gochain#422]
https://www.rosetta-api.org/

**Comment by jmank88** [comment]
We should be able to minimally modify the official reference implementation for ethereum based on geth, without any changes to this repo.
https://github.com/coinbase/rosetta-ethereum

**Comment by treeder** [comment]
Ya, @r-gochain is already trying that.

**Comment by r-gochain** [comment]
Doesn't work out of the box :(

Command Failed: request failed: /network/status {Code:2 Message:geth error Description:<nil> Retriable:false Details:map[context:Post "enode://a5893e5634503a1223c15842a29788f1ef87e3a19f75664819b670afa8a326742e9b1a2c7507c45c2e74a85516fb210d30f76da8bdbda13db1f07aefb26825d1@35.228.129.142:30303": unsupported protocol scheme "enode"]}: unable to initialize asserter

Trying to debug

**Comment by jmank88** [comment]
Were you running the existing code? AFAIK it is hard coded for eth mainnet and ropsten only, and depends on chain config, genesis block, etc. We just need to add or swap in a `gochain/` dir analogous to the `ethereum/` one, and add or replace the `ethereum.*` references.

**Comment by r-gochain** [comment]
Yep that what I've done, struggling with crypto package binary dependencies (gcc fails to compile)

**Comment by r-gochain** [comment]
https://github.com/gochain/rosetta
