### ISSUE TITLE
Darvaza Fork: GIP 29 & 30

### ISSUE THREAD

**Issue by jmank88** [gochain/gochain#423]
The Darvaza fork implements gochain/gips/issues/30 (Burn all gas fees), and automates gochain/gips/issues/29 (Increase minimum gas price by 1000x) at the same time.

- [x] Implementation #420 (^v3.4.1)

### Effective blocks:

- [x] testnet 16811000
- [x] mainnet 17900000 (March 17th, 2pm UTC)

## Testnet testing

We'll want to try common wallets and tools to ensure they don't have some kind of thing that limits gas prices. 

* [x] Test metamask
* [ ] Test trust wallet
* [x] Test web3 cli
* [ ] Test web3.js
* [x] Explorer wallet (private key)
* [x] Turbo Wallet
* [ ] others?

**Comment by jmank88** [comment]
The implementation is complete and will take effect on the _testnet_ at block # 16811000 (around unix time ~1614371340 or Fri Feb 26 2021 20:29:00 GMT+0000).

**Comment by treeder** [comment]
Added a few tools/clients to test to this ticket.
