### ISSUE TITLE
TRANSFERED GO FROM KUCOIN MAIN ACCOUNT TO LEDGER WALLER NOW THEY ARE GONE!

### ISSUE THREAD

**Issue by SPART20** [gochain/gochain#434]
Can someone please help me !!! I transferred 6,700 Go tokens from Kucoin main account to my ledger Nano wallet, thinking that since it was an erc20 token it would be ok,........ they are all gone, never made it to my wallet! CAN ANYTHING BE DONE???

**Comment by treeder** [comment]
Wow, can you please use more caps and exclamation marks next time so we know you're serious? 

Here, let me google that for you: https://www.google.com/search?q=ledger+gochain

**Comment by SPART20** [comment]
I know right lol . so upset.

________________________________

**Comment by SPART20** [comment]
thanks for replaying. Not sure I understand, once I set up the Ether wallet, how do I find the tokens since the transfer was done two weeks ago? thanks
