### ISSUE TITLE
Lost my GO tokens when trying to deposit off of kucoin exchange account to ledger nano!

### ISSUE THREAD

**Issue by SPART20** [gochain/gochain#435]
Hi need help please. two weeks ago tried to deposit Go token from kucoin account to ledger namo, on the kucoin side it says it was completed, BUT do not have the tokens in the cold wallet. I was told to install myeitherwallet (MEW) i did that and changed the network to GOchain.io on top right but what do i do after that. How do i find the tokens? thanks in advance

**Comment by treeder** [comment]
1) Please don't open new issues for the same thing you already have an issue for.
2) Please don't post your issues with your wallet or exchanges, or whatever has nothing to do with the gochain software here. 

You can post questions in discussions over here: https://github.com/gochain/docs/discussions if you'd like, but again, please don't double post and stop using exclamation marks and please google around before asking.
