### ISSUE TITLE
Supply Stats API not working. 

### ISSUE THREAD

**Issue by silentresearch** [gochain/gochain#439]
I have set the initial allocation in the genesis.json as follows:
```
"alloc": {
    "0xF2cBFB1dd50601610e9c4a699780f14415e84e83": {
      "balance": "0x33b2e3c9fd0803ce8000000"
    }
  },
```
I always get the same response: code":-32000,"message":"unknown initial allocation"

**Comment by treeder** [comment]
dupe: https://github.com/gochain/docs/discussions/121

**Comment by cppfuns** [comment]
> dupe: [gochain/docs#121](https://github.com/gochain/docs/discussions/121)
Still unresolved
