### ISSUE TITLE
Node not restarting 

### ISSUE THREAD

**Issue by bigpopcorn** [gochain/gochain#445]
>Error response from daemon: network 432aa7dbb5072d4f4409086f5fdb4953af4fc69747d9bcd2a7ffe6c2d79638b3 not found
Error: failed to start containers: node

**Comment by treeder** [comment]
Gonna need more info.

**Comment by bigpopcorn** [comment]
Nov 11 17:10:26 NY1ACNSGOCHAI01 dockerd[5436]: time="2021-11-11T17:10:26.522934426Z" level=warning msg="error locating sandbox id 3b47b96547eece54f5b3b10703c3fa421aef04c91cf8729ca4c874bda2367dd3: sandbox 3b47b96547eece54f5b3b10703c3fa421
aef04c91cf8729ca4c874bda2367dd3 not found"
Nov 11 17:10:26 NY1ACNSGOCHAI01 dockerd[5436]: time="2021-11-11T17:10:26.524466116Z" level=error msg="ec7645bdd497fd05f65e89094a635c31e68f75361e3b47ff4de27506b7e47efa cleanup: failed to delete container from containerd: no such container
