### ISSUE TITLE
The node suddenly hangs when it is running

### ISSUE THREAD

**Issue by hanzhenlong1314** [gochain/gochain#446]
May I ask what caused this  ，This is the log of the node suddenly crashing

content:gs     0x0
content:fs     0x0
content:cs     0x33
content:rflags 0x206
content:rip    0x7f40686393d7
content:r15    0x0
content:r14    0x16435f4
content:r13    0x0
ontent:r12    0x7f36c80008c0
content:r11    0x206
content:r10    0x8
content:r9     0x7f4038e79700
content:r8     0xa

content:rsp    0x7f4038e78928

content:rbp    0x16e4c46
content:rsi    0x14
content:rdi    0xa
content:rdx    0x6
content:rcx    0xffffffffffffffff
content:rbx    0x7f40689cb868
content:rax    0x0
content:
content:	/work/install/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/util/buffer_pool.go:240 +0x18c

content:created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool

content:	/work/install/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/util/buffer_pool.go:209 +0x128

content:github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc001c457a0)

content:goroutine 33295885 [select]:

content:
content:	/work/install/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db.go:156 +0x5c7

content:created by github.com/syndtr/goleveldb/leveldb.openDB

	/work/install/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db_compaction.go:773 +0x145

content:github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc00e1a8700

content:goroutine 39938959 [select, 1263 minutes]:

content:

content:	/work/go/src/net/http/server.go:2969 +0x36c

content:created by net/http.(*Server).Serve

content:	/work/go/src/net/http/server.go:1950 +0xa14

content:net/http.(*conn).serve(0xc01f2019a0, 0x1696d60, 0xc02f075640)

content:	/work/go/src/bufio/bufio.go:139 +0x4f

content:bufio.(*Reader).Peek(0xc030e68060, 0x4, 0x13d61c5551cc1, 0x2279d20, 0x0, 0x0, 0x2279d20)

**Comment by treeder** [comment]
Can you try these fixes and see if it resolves the issue: https://github.com/gochain/gochain/discussions/443
